name: Test and vet code

on:
  push:
    branches:
      - feature-*

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.4'

      - name: Vet code
        run: |
          make vet

  tests: 
    runs-on: ubuntu-latest
    needs: vet
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.4'

      - name: Run Integration Tests
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          WARCRAFTLOGS_API_TOKEN: ${{ secrets.WARCRAFTLOGS_API_TOKEN }}
          REDIS_ADDR: localhost:6379
        run: |
          make test