name: Test and Release Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.4'

      - name: Vet code
        run: |
          make vet

  tests: 
    runs-on: ubuntu-latest
    needs: vet
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.4'

      - name: Run Integration Tests
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIS_ADDR: localhost:6379
        run: |
          make test

  release:
    runs-on: ubuntu-latest
    needs: 
      - vet
      - tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t alexrsit/armory:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: alexrsit
          password: ${{ secrets.DOCKER_PAT }}

      - name: Push Docker Image
        run: |
          docker push alexrsit/armory:latest
